### ISSUE TITLE
Tumor deformations

### ISSUE THREAD

**Issue by lajipeng** [cwmok/DIRAC#4] opened 2022-12-01 08:07 UTC
Hi, thank you for your excellent work.  This work is really meaningful and seems to indeed solve the clinical challenges. 
However, I have the following questions and hope to figure them out.
First, is there any deformation between the pre-operative and follow-up scans? As shown in Fig.2 of your paper, I guess that there are no severe deformations because most parts are aligned between the pre-operative and follow-up scans. But the results show that the tumor has a large deformation. So I worry about the rationality behind it.  
Second, if we get the forward prediction ubf, why the inverse transformation ufb is not -ubf? Maybe it doesn't need another prediction?

**Comment by cwmok** [comment] 2022-12-01 08:34
Hi @lajipeng,

>> First, is there any deformation between the pre-operative and follow-up scans? As shown in Fig.2 of your paper, I guess that there are no severe deformations because most parts are aligned between the pre-operative and follow-up scans. But the results show that the tumor has a large deformation. So I worry about the rationality behind it.

Ans: Yes, the main source of misalignment is caused by tumor's mass effect and tumor resection. Since the pre-operative and follow-up scans are pre-affine registered to a standard atlas. You will observe there are only little affine misalignments such as translation and rotation etc. However, the non-linear deformation between the pre-operative and follow-up scans cannot be resolved by the affine/rigid registration, which is the main goal of this work. Yet, in some extreme cases, the misalignment can be up to ~30 mm. For more details, you may refer to the BraTS-Reg dataset, which is publicly available at https://www.med.upenn.edu/cbica/brats-reg-challenge/.

>> Second, if we get the forward prediction ubf, why the inverse transformation ufb is not -ubf? Maybe it doesn't need another prediction?

Ans: The inverse transformation of ufb is not as trivial as -1*ufb. This [paper ](https://www.sciencedirect.com/science/article/pii/S1053811907005848?casa_token=Lpn-EAzhfMAAAAAA:dbaF079V4hAcowqtqW2FZNyCgfUU13c5au5DoVNmUoAe110aZf5w_A_LuwKiDzPydxd_UH8O3Q) (see Figure. 1) offers a great explanation about the fallacy of true inverse transformation. Moreover, due to the missing correspondence problem caused by tumor mass effect, the groundtruth deformation field of the tumor region is absent/not well defined in general. In our approach, we aim to maximize the similarity between the regions with valid correspondence while ignoring the similarity measure in regions with absent correspondence in order to alleviate the impact of the tumor mass effect on the registration.

**Comment by lajipeng** [comment] 2022-12-01 09:24
@cwmok Thanks very much. I get it~

**Closed as completed** 2022-12-01 09:24 UTC
